spring.application.name=demo

# 1. Connection Details
spring.datasource.url=jdbc:mysql://localhost:3306/ssms?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# 2. Hibernate Strategy (The Magic Part)
# 'update' tells Spring to automatically create tables for you
spring.jpa.hibernate.ddl-auto=update

# 3. SQL Logging (So you can see what's happening)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Tell Spring to throw an exception if no handler is found
spring.mvc.throw-exception-if-no-handler-found=true
# Disable the default resource handling so it doesn't try to look for a "static file" 404
spring.web.resources.add-mappings=false